amcl:
  ros__parameters:
    use_sim_time: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65

# planner_server:
#   ros__parameters:
#     expected_planner_plugins: ["Nav2StraightLinePlanner"]
#     Nav2StraightLinePlanner:
#       plugin: "nav2_straightline_planner/StraightLine"
#       interpolation_resolution: 0.1
#     use_sim_time: true

planner_server:
  ros__parameters:
    planner_plugins: ["RRTStarPlanner"]
    RRTStarPlanner:
      plugin: "rrtstar_planner/RRTStarPlanner"
      iterations: 300
      turn_radius: 2.0
      rho_multiplier: 5.0
      search_radius_mult: 2.0
      goal_tolerance: 2.0
      dubins_step_size: 0.05
    use_sim_time: true

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_speed_xy: 0.26
      min_speed_xy: 0.0
      max_speed_theta: 1.0
      min_speed_theta: -1.0
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      critics: [
        "ObstacleFootprintCritic",
        "GoalAlignCritic",
        "PathAlignCritic",
        "GoalDistCritic",
        "PreferForwardCritic",
        "RotateToGoalCritic"
      ]
      ObstacleCritic:
        scale: 0.02
      GoalAlignCritic:
        scale: 24.0
      PathAlignCritic:
        scale: 32.0
      GoalCritic:
        scale: 24.0
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_nav_to_pose_bt_xml: "navigate_w_replanning_time2pose.xml"
    default_nav_through_poses_bt_xml: "navigate_w_replanning_time2poses.xml"

behavior_server:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true

smoother_server:
  ros__parameters:
    use_sim_time: true

velocity_smoother:
  ros__parameters:
    use_sim_time: true
